--- #YAML:1.0
name:               MojoX-Logite
version:            0.01
abstract:           A simple Mojo::Log implementation which logs to an SQLite database
author:
    - Alberto Attilio Reggiori <areggiori@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:  1.0
    ORLite:       1.47
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
